### ISSUE TITLE
Feedback for t3-arrays-hashes

### ISSUE THREAD

**Issue by kripple** [JamesAnthonyLow/JamesAnthonyLow.github.io#20]
Stuff I liked:
- Links in the body to Wikipedia & Ruby Docs
- Excited tone of the post

Typos:
- In the paragraph "Ok so far ...", you've got a sentence that spells hash 'has'

Potential Additions:
- Maybe change the light yellow text color to something darker / with more contrast. I can read it just fine, but people can be weird about yellow
- Include more information about the more basic concepts you talk about (i.e objects, the enumerable module)

**Comment by JamesAnthonyLow** [comment]
Thank you Kelly, your feedback is greatly appreciated!
